namespace HOA {

	public enum EToken {
		TREE,
		KATA, CARA, MAWT, KABU, HSIL,
		DEMO, MINE, MEIN, PANO, DECI, HSTE,
		ROOK, SMAS, CONF, ASHE, BATT, GARG, HSTO,
		GRIZ, TALO, META, ULTR, HFIR,
		REVO, APER, PIEC, REPR, OLDT, HBRA,
		BEES, MYCO, MART, LICH, WEBB, BLAC, HSLK,
		PRIS, AREN, PRIE, DREA, HGLA,
		RECY, NECR, MOUT, MONO, HBLO,
		CORP, ROCK, HILL, MNTN, WATR, LAVA,
		NONE
	}

	public enum EPlane {SUNK, GND, AIR, ETH}
	public enum EClass {UNIT, OB, KING, TRAM, DEST, REM, HEART, CELL}
	public enum EStat {HP, MHP, DEF, IN, AP, FP, STUN, COR}

	public enum EAim {CELLMATE, NEIGHBOR, PATH, LINE, ARC, FREE, SELF, GLOBAL, OTHER}
	public enum EPurpose {MOVE, CREATE, ATTACK, OTHER}

	public enum ELog {IN, OUT, IO, DEBUG};
	
	public enum ETip {NONE, CELL, DEST, REM, KING, TRAM, HEART, ONDEATH, AP, FP, IN, DEF, HP, SELF, NEIGHBOR, PATH, LINE, ARC, FREE, GLOBAL, UNIT}
	
	public enum EEffect {NONE, SHOW, BIRTH, DEATH, DMG, STATUP, STATDOWN, 
		FIRE, EXP, LASER, COR, STUN, HEADS, TAILS, DESTRUCT, SHUFFLE, ADVANCE,
		CORRODE, WATERLOG, INCINERATE, STICK, DETONATE, BURROW}

	public enum EDice {COIN, D4, D6, D8, D10, D12, D20}

}