
namespace HOA.Tokens
{
    /// <summary>
    /// Simple enum of Token species.  None = 0.
    /// </summary>
    public enum Species : short
    {
        None = 0,
        Antenna,
        Aperture,
        Arena, 
        Ashes,
        Beesassin,
        BlackWinnow,
        BloodHeart,
        BombingRange,
        BrassHeart,
        Carapace,
        Conflagragon,
        Corpse,
        Cottage,
        Curse,
        Decimatrix,
        Demolitia,
        DreamReaver,
        Exhaust,
        FirHeart,
        Gap,
        Gargoliath,
        Gatecreeper,
        GlassHeart,
        Grizzly,
        Hill,
        House,
        Ice,
        Kabutomachine,
        Katandroid,
        Lava,
        Lichenthrope,
        ManTrap, 
        Mawth,
        MeinSchutz,
        Metaterrainean,
        Mine,
        Monolith,
        Mountain,
        Mycolonist,
        Necro,
        OldThreeHands,
        Panopticannon,
        Piecemaker,
        Priest,
        PrismGuard,
        Pylon,
        Pyramid,
        Quicksand,
        Rambuchet,
        Rampart,
        Recyclops,
        Reprospector,
        RevolvingTom,
        Rock,
        Rook,
        Sand,
        SiliconHeart,
        SilkHeart,
        Smashbuckler,
        SteelHeart,
        StoneHeart,
        TalonedScout, 
        Temple,
        TimeWell,
        TimeSink,
        Tree,
        Tree3,
        Tree2,
        Tree4, 
        Ultratherium, 
        Water,
        Web 
         
        
    }



}