namespace FBI.Tokens {
	
	public enum TokenValue {
		NONE,
		NINJOID, SENTINEL, MOTH, STAGBOT, 
		DEMOLITIA, CONDOR, MINE, PANOPTICLOPS, ROBOTANK,
		MOURNKING, PHOENIX, PHOENIXASH, RAMBUCHET, DRAGON,
		GRIZZLY, OWL, GOLEM, YETI,
		GUNSLINGER, PIECEMAKER, PORTAL, CHIEF, GRANDDAD,
		LARVA, BEE, SHROOMAN, PLANT, SPIDER,
		GLASSMAN, HAZE, PRIEST, SULTAN,
		FIEND, CHANCELLOR, VOIDGATE, MAGMAN, MONOLITH,
		
		MOUNTAIN,
		HILL, LAKE, 
		TREE, BOULDER, SHACK,
		CORPSE
	}					
}
