namespace HOA {

	public enum EToken {
		TREE,
		KATA, CARA, MAWT, KABU, HSIL,
		DEMO, MINE, MEIN, PANO, DECI, HSTE,
		ROOK, SMAS, CONF, ASHE, BATT, GARG, HSTO,
		GRIZ, TALO, META, ULTR, HFIR,
		REVO, APER, PIEC, REPR, OLDT, HBRA,
		BEES, MYCO, MART, LICH, WEBB, BLAC, HSLK,
		PRIS, AREN, PRIE, DREA, HGLA,
		RECY, NECR, GATE, MONO, HBLO,
		CORP, ROCK, HILL, MNTN, WATR, LAVA,
		NONE
	}



	public enum EEffect {NONE, SHOW, BIRTH, DEATH, DMG, STATUP, STATDOWN, 
		FIRE, EXP, LASER, COR, STUN, HEADS, MISS, DESTRUCT, SHUFFLE, ADVANCE,
		CORRODE, WATERLOG, INCINERATE, STICK, DETONATE, BURROW, FLY, WALK, TELEPORT,
		GETHEART, OWNER}


}